# -*- coding: utf-8 -*-
"""PRODIGY_GA_04_Image_to_Image_Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-IdwBTK1cC-AWPsb2aMc2-KjryWscrBe
"""

from PIL import Image, ImageFilter
import matplotlib.pyplot as plt

# Load image
image = Image.open("/content/sample_data/robot/Screenshot 2026-06-26 221041.png")

# Image-to-Image Translation (Contour Filter)
translated = image.filter(ImageFilter.CONTOUR)

plt.figure(figsize=(10,5))

plt.subplot(1,2,1)
plt.imshow(image)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1,2,2)
plt.imshow(translated)
plt.title("Translated Image")
plt.axis("off")

plt.show()